package com.vova7865.soulbound;

import java.util.ArrayList;
import java.util.List;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.enchantment.EnumEnchantmentType;
import net.minecraftforge.common.MinecraftForge;

@Mod(modid = Main.MODID, version = Main.VERSION)
public class Main {
	public static final String NAME = "Soulbound Enchantment";
	public static final String MODID = "soulboundench";
	public static final String VERSION = "1.0";

	public static EnchantmentSoulbound soulbound;
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata modMeta = event.getModMetadata();
		modMeta.autogenerated = false;
		List<String> list = new ArrayList<String>();
		list.add("vova7865");
		modMeta.authorList = list;
		modMeta.modId = Main.MODID;
		modMeta.version = Main.VERSION;
		modMeta.name = NAME;
		modMeta.description = "A mod that adds a Soulbound enchantment, which keeps your items with you on death";
	}
	@EventHandler
	public void init(FMLInitializationEvent event) {
		soulbound = new EnchantmentSoulbound(getEmptyEnchantId(), 1, EnumEnchantmentType.all);
	}

	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {
		MinecraftForge.EVENT_BUS.register(new Events());
	}
	
	private int getEmptyEnchantId() {
		for (int i = 0; i < Enchantment.enchantmentsList.length; i++)
			if (Enchantment.enchantmentsList[i] == null)
				return i;

		return -1;
	}
}
